name: main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Elixir/Erlang Setup
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.13.4'
          otp-version: '25.0'
      - name: Restore deps cache
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install deps
        run: mix deps.get
      - name: Format
        run: mix format --check-formatted
      - name: Compiler warnings
        run: mix compile --warnings-as-errors
      - name: Credo strict
        run: mix credo --strict
  
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir:
          - '1.13'
        otp:
          - '25.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Elixir/Erlang setup
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install deps
        run: mix deps.get
      - name: tests
        env:
          MIX_ENV: test
        run: mix test
    